# Generated by Django 4.0 on 2021-12-17 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('btest', '0003_alter_bb_options_alter_rubric_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spisokperiodov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pacient', models.CharField(max_length=30, verbose_name='Пациент')),
                ('datapostuplenija', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата поступления')),
                ('diagnoz', models.TextField(blank=True, null=True, verbose_name='Диагноз')),
                ('datavypiski', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата выписки')),
                ('palata', models.CharField(max_length=3, verbose_name='Палата')),
                ('rubric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='btest.rubric', verbose_name='Рубрика')),
            ],
            options={
                'verbose_name': 'Амбулаторный период',
                'verbose_name_plural': 'Амбулаторные периоды',
                'ordering': ['-datapostuplenija'],
            },
        ),
        migrations.CreateModel(
            name='Mapclient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familija', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('otchestvo', models.CharField(max_length=20, verbose_name='Отчество')),
                ('nomer', models.CharField(max_length=10, verbose_name='Номер')),
                ('strahovojpolis', models.CharField(max_length=16, verbose_name='Номер страхового полиса')),
                ('datecreation', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата поступления')),
                ('patientaddress', models.CharField(max_length=70, verbose_name='Адрес пациента')),
                ('passportseries', models.CharField(max_length=4, verbose_name='Серия паспорта')),
                ('passportid', models.CharField(max_length=6, verbose_name='Номер паспорта')),
                ('rubric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='btest.rubric', verbose_name='Рубрика')),
            ],
            options={
                'verbose_name': 'Карта пациента',
                'verbose_name_plural': 'Карты пациентов',
                'ordering': ['-datecreation'],
            },
        ),
        migrations.CreateModel(
            name='Bolnichnyepalaty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jetazh', models.CharField(max_length=9, verbose_name='Этаж')),
                ('nomer', models.CharField(max_length=3, verbose_name='Номер')),
                ('vmeshhaemost', models.CharField(max_length=2, verbose_name='Вместимость')),
                ('rubric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='btest.rubric', verbose_name='Рубрика')),
            ],
            options={
                'verbose_name': 'Больничная палата',
                'verbose_name_plural': 'Больничные палаты',
                'ordering': ['-nomer'],
            },
        ),
    ]
