# Generated by Django 4.0 on 2021-12-17 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('btest', '0004_spisokperiodov_mapclient_bolnichnyepalaty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bolnichnyepalaty',
            name='rubric',
        ),
        migrations.RemoveField(
            model_name='mapclient',
            name='rubric',
        ),
        migrations.RemoveField(
            model_name='spisokperiodov',
            name='rubric',
        ),
    ]
