# Generated by Django 4.0 on 2021-12-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btest', '0005_remove_bolnichnyepalaty_rubric_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spisokperiodov',
            name='datavypiski',
            field=models.CharField(max_length=12, verbose_name='Дата выписки'),
        ),
    ]
