# Generated by Django 4.0 on 2021-12-16 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('btest', '0002_rubric_alter_bb_content_alter_bb_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bb',
            options={'ordering': ['-published'], 'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterModelOptions(
            name='rubric',
            options={'ordering': ['name'], 'verbose_name': 'Рубрика', 'verbose_name_plural': 'Рубрики'},
        ),
    ]
