# Generated by Django 4.0 on 2021-12-18 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('btest', '0006_alter_spisokperiodov_datavypiski'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bb',
        ),
        migrations.DeleteModel(
            name='Rubric',
        ),
    ]
